openapi: 3.0.5
info:
  title: OpenAPIテスト
  version: 1.0.0
  description: OpenAPIテスト
servers:
  - url: http://localhost:3000/api/v1
    description: Local server
  - url: https://staging.test.tokyo/api/v1
    description: Staging server
security:
  - bearerAuth: []
paths:
  /prefs:
    get:
      summary: Get all prefs
      description: 全ての県を取得
      responses:
        200:
          description: 全ての県を返す
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 200
                  prefs:
                    type: array
                    items:
                      $ref: '#/components/schemas/Pref'
        400:
          description: 作成エラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Failure
  /pref/{prefId}:
    get:
      summary: Get Single pref
      description: prefIdの県情報を返す
      parameters:
      - name: "prefId"
        in: "path"
        description: "取得したい県のID"
        required: true
        type: "string"
      responses:
        200:
          description: prefIdの県情報を返す
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 200
                  pref:
                    $ref: '#/components/schemas/Pref'
        400:
          description: 作成エラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Failure                    
components:
  schemas:
    Pref:
      type: object
      properties:
        id:
          type: integer
          example: 12
          description: primary id
        name:
          type: string
          example: 千葉
          description: 県名