openapi: 3.0.5
info:
  title: OpenAPIテスト
  version: 1.0.0
  description: OpenAPIテスト
servers:
  - url: http://localhost:3000/api/v1
    description: Local server
  - url: https://staging.test.tokyo/api/v1
    description: Staging server
security:
  - bearerAuth: []
paths:
  /area/{zipCode}:
    get:
      summary: Get Area
      description: zipCodeから地域を返す
      parameters:
      - name: "zipCode"
        in: "path"
        description: "取得したい地域の郵便番号"
        required: true
        type: "string"
      responses:
        200:
          description: 地域の情報を返す
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 200
                  area:
                    $ref: '#/components/schemas/Area'
        400:
          description: 作成エラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Failure                    
components:
  schemas:
    Area:
      type: object
      properties:
        zipCode:
          type: string
          example: 274-0077
          description: 郵便番号
        name:
          type: string
          example: 千葉船場市薬円台3丁目
          description: 地域情報